# =====================================================================
# Wave Theory Chatbot - Main Configuration File
# =====================================================================

app:
  name: "Wave Theory Chatbot"
  version: "1.0.0"
  debug: false
  port: 8501

physics:
  force_law:
    G: 1.0
    wave_frequency: 0.5
    decay_length: 10.0
  simulation:
    dt: 0.01
    max_particles: 100
    domain:
      x: [-100, 100]
      y: [-100, 100]
      z: [-100, 100]

neural_network:
  architecture:
    input_size: 4  # [t, x, y, z]
    output_size: 1  # scalar field
    hidden_layers: 6
    neurons_per_layer: 128
    activation: "tanh"
  
  training:
    learning_rate: 0.001
    lr_decay_rate: 0.99
    lr_decay_steps: 1000
    batch_size: 256
    n_epochs: 10000
    
  loss_weights:
    data: 1.0
    physics: 1.0
    boundary: 1.0
    initial: 1.0
    
  collocation:
    n_points: 10000
    adaptive_sampling: true
    high_residual_ratio: 0.5

symbolic_regression:
  populations: 15
  population_size: 33
  max_size: 20
  max_depth: 10
  n_iterations: 100
  
  operators:
    binary: ["+", "-", "*", "/", "^"]
    unary: ["sin", "cos", "exp", "log", "sqrt", "tanh"]
  
  quality_diversity:
    use_frequency: true
    adaptive_parsimony: 20.0
    parsimony: 0.0032
  
  optimization:
    algorithm: "BFGS"
    n_restarts: 2
    probability: 0.14
    iterations: 8

chatbot:
  model: "microsoft/DialoGPT-small"
  max_length: 200
  temperature: 0.7
  top_p: 0.9
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/wave_theory.log"
